// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/aprender": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/retaguarda": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/aprender" | "/login" | "/retaguarda" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./aprender/page.jsx": {
    id: "aprender/page";
    page: "/aprender";
  };
  "./login/page.jsx": {
    id: "login/page";
    page: "/login";
  };
  "./retaguarda/page.jsx": {
    id: "retaguarda/page";
    page: "/retaguarda";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "aprender/page": typeof import("./src/app/./aprender/page.jsx");
  "login/page": typeof import("./src/app/./login/page.jsx");
  "retaguarda/page": typeof import("./src/app/./retaguarda/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};