// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/aprender": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/pagamento/sucesso": {
    params: {};
  };
  "/planos": {
    params: {};
  };
  "/retaguarda": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/aprender" | "/dashboard" | "/login" | "/pagamento/sucesso" | "/planos" | "/retaguarda" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./aprender/page.jsx": {
    id: "aprender/page";
    page: "/aprender";
  };
  "./dashboard/page.jsx": {
    id: "dashboard/page";
    page: "/dashboard";
  };
  "./login/page.jsx": {
    id: "login/page";
    page: "/login";
  };
  "./pagamento/sucesso/page.jsx": {
    id: "pagamento/sucesso/page";
    page: "/pagamento/sucesso";
  };
  "./planos/page.jsx": {
    id: "planos/page";
    page: "/planos";
  };
  "./retaguarda/page.jsx": {
    id: "retaguarda/page";
    page: "/retaguarda";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "aprender/page": typeof import("./src/app/./aprender/page.jsx");
  "dashboard/page": typeof import("./src/app/./dashboard/page.jsx");
  "login/page": typeof import("./src/app/./login/page.jsx");
  "pagamento/sucesso/page": typeof import("./src/app/./pagamento/sucesso/page.jsx");
  "planos/page": typeof import("./src/app/./planos/page.jsx");
  "retaguarda/page": typeof import("./src/app/./retaguarda/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};